import React, { useContext, useEffect, useState } from 'react'
import BookCard from './BookCard';
import image1 from "../assets/paradox.png"
import image2 from "../assets/mist.png"
import image3 from "../assets/ecos.png"
import { themeContext } from '../Context/ThemeContext';
const books = [
    {
      title: "Science Fiction",
      imageUrl: image1, // Replace with actual image URLs or imports
      description: `"As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."`,
      link: "#"
    },
    {
      title: "Mystery",
      imageUrl: image2,
      description: `"The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light..."`,
      link: "#"
    },
    {
      title: "Fantasy",
      imageUrl: image3,
      description: `"The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath..."`,
      link: "#"
    }
  ];
const SampleBooks = () => {
  const {theme} = useContext(themeContext)
    return (
      <div className="py-12">
        <div className=" mx-auto px-4">
          <h2 className={`text-center text-2xl font-semibold ${theme === 'light' ? "text-black":"text-white"} mb-8`}>Sample Books Generated by BookAI</h2>
          <p className={`text-center ${theme === 'light' ? "text-black":"text-white"} mb-12`}>Explore some of the captivating books created using our AI technology.</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {books.map((book, index) => (
              <BookCard key={index} book={book} />
            ))}
          </div>
        </div>
      </div>
    );
  };
  
  export default SampleBooks;

